# File 2: Swagger File for API Gateway

swagger: '2.0'
info:
  title: Orderful API Gateway
  version: '1.0'
basePath: /dev
schemes:
  - https
paths:
  /webhook:
    post:
      produces:
        - application/json
      responses:
        '200':
          description: OK
      x-amazon-apigateway-integration:
        uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProcessPayloadFunction.Arn}/invocations'
        httpMethod: POST
        type: aws_proxy
        responses:
          default:
            statusCode: '200'
